apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mirrorverse.serviceAccountName" . }}
  labels:
    {{- include "mirrorverse.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrorverse
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mirrorverse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mirrorverse
subjects:
  - kind: ServiceAccount
    name: mirrorverse
    namespace: {{ .Release.Namespace }}